<template>
    <div>
        <headerSuites/>
        <navSuites/>
        <gallerySuites/>
        <infoSuites/>
        <iconsServices/>
        <generalServices/>
        <listServices/>
    </div>
</template>
